### ISSUE TITLE
执行fie init nuke报错

### ISSUE THREAD

**Issue by haish007** [fieteam/fie#46]
D:\project\nukedemo>fie init nuke
'tnpm' 
[fie-error] 运行报错, 请在这里反馈问题给 @擎空 @宇果 https://github.com/fieteam/fie/issues/new
C:\Users\Donnie123\.fie\node_modules\.4.2.0@koa-bodyparser\index.js:72
  return async function bodyParser(ctx, next) {
               ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Donnie123\.fie\node_modules\.0.0.5@fie-toolkit-nuke\weex-devtool\lib\DebugServer.js:9:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

**Comment by hugohua** [comment]
已经修复了

**Comment by haish007** [comment]
D:\project\nukedemo>fie init nuke
'tnpm' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
�������ļ�
[fie-error] 运行报错, 请在这里反馈问题给 @擎空 @宇果 https://github.com/fieteam/fie/issues/new
C:\Users\Donnie123\.fie\node_modules\.4.2.0@koa-bodyparser\index.js:72
  return async function bodyParser(ctx, next) {
               ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Donnie123\.fie\node_modules\_fie-toolkit-nuke@0.0.5@fie-toolkit-nuke\weex-devtool\lib\DebugServer.js:9:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)


问题好像还没修复，依然报一样的错误
