### ISSUE TITLE
fie qnproxy run  怎么试用

### ISSUE THREAD

**Issue by molinweb** [fieteam/fie#53]
E:\workspace_qap_jy>fie qnproxy run
'tnpm' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
�������ļ�
[fie-error] 运行报错, 请在这里反馈问题给 @擎空 @宇果 https://github.com/fieteam/fie/issues/new 
C:\Users\molin\.fie\node_modules\_koa-logger@3.1.0@koa-logger\index.js:36
  return async function logger (ctx, next) {
               ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\molin\.fie\node_modules\_fie-plugin-qnproxy@0.1.15@fie-plugin-qnproxy\lib\run.js:9:16)
    at Module._compile (module.js:570:32)

E:\workspace_qap_jy>fie -h

 fie 使用帮助:  $ fie [command] [options]

    $  fie                     显示fie帮助信息,若目录下有使用的套件,则会同时显示套件的帮助信息
    $  fie init [toolkitName]  初始化套件
    $  fie install [name]      安装FIE模块
    $  fie update [name]       更新FIE模块
    $  fie list [type]         插件列表
    $  fie ii                  安装npm模块，功能等同于npm install，但安装速度更快更稳定
    $  fie clear               清空 fie 的本地缓存
    $  fie switch              切换 fie 的开发环境
    $  fie help                显示套件帮助信息
    $  fie [name]              其他调用插件命令

   Options:

     -h, --help                显示fie帮助信息
     -v, --version             显示fie版本

 提示: 
   套件 - 若想查看项目中所使用的套件帮助信息,请在项目根目录执行该命令.
   插件 - 若想查看插件的帮助信息,请使用 fie [name] help 命令, eg : fie git help
   环境 - 当前FIE开发环境为: 外网环境 , 可使用 $ fie switch 进行切换

E:\workspace_qap_jy>fie qnproxy
'tnpm' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
�������ļ�
[fie-error] 运行报错, 请在这里反馈问题给 @擎空 @宇果 https://github.com/fieteam/fie/issues/new 
C:\Users\molin\.fie\node_modules\_koa-logger@3.1.0@koa-logger\index.js:36
  return async function logger (ctx, next) {
               ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\molin\.fie\node_modules\_fie-plugin-qnproxy@0.1.15@fie-plugin-qnproxy\lib\run.js:9:16)
    at Module._compile (module.js:570:32)

**Comment by hugohua** [comment]
看起来是node版本不够高，建议升级到 6.x
