### ISSUE TITLE
  return async function bodyParser(ctx, next) {

### ISSUE THREAD

**Issue by y7280** [fieteam/fie#57]
please help to see what is wrong:

E:\>qap init mkt
mkdir: path already exists: E:/mkt
'tnpm' 
[fie-error] 运行报错, 请在这里反馈问题给 @擎空 @宇果 https://github.com/fieteam/
fie/issues/new
C:\Users\Administrator\.fie\node_modules\_koa-bodyparser@4.2.0@koa-bodyparser\in
dex.js:72
  return async function bodyParser(ctx, next) {
               ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Administrator\.fie\node_modules\_fie-toolkit
-nuke@0.7.35@fie-toolkit-nuke\weex-devtool\lib\DebugServer.js:9:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

**Comment by chengzhixuan** [comment]
我也碰到这个问题qap clear清下缓存 在运行我的就好了

**Comment by hugohua** [comment]
node版本太低了，建议6.x 以上
