### ISSUE TITLE
Unexpected token function

### ISSUE THREAD

**Issue by chengzhixuan** [fieteam/fie#63]
![qq 20171030143115](https://user-images.githubusercontent.com/21271619/32157532-03e15b44-bd7f-11e7-9d11-dd29c880843d.png)

**Comment by chengzhixuan** [comment]
已经解决

**Comment by lz916** [comment]
[fie-error] 运行报错, 请在这里反馈问题给 @擎空 @宇果 https://github.com/fieteam/fie/issues/new
C:\Users\Administrator.GZA4DIHVGZVI7NK\.fie\node_modules\_koa-bodyparser@4.2.0@koa-bodyparser\index.js:72
  return async function bodyParser(ctx, next) {
               ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Administrator.GZA4DIHVGZVI7NK\.fie\node_modules\_fie-toolkit-nuke@0.7.36@fie-toolkit-nuke\weex-devtool\lib\DebugServer.js:9:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
