### ISSUE TITLE
'tnpm' 运行报错, 

### ISSUE THREAD

**Issue by haughtys** [fieteam/fie#65]
'tnpm' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
�������ļ�
[fie-error] 运行报错, 请在这里反馈问题给 @擎空 @宇果 https://github.com/fieteam/fie/issues/new
TypeError: Cannot read property 'ret' of undefined
    at WebSocket.<anonymous> (C:\Users\Administrator\.fie\node_modules\_fie-toolkit-nuke@0.7.36@fie-toolkit-nuke\weex-devtool\lib\router\Websocket.js:288:67)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver.ontext (C:\Users\Administrator\.fie\node_modules\_ws@1.1.5@ws\lib\WebSocket.js:841:10)
    at C:\Users\Administrator\.fie\node_modules\_ws@1.1.5@ws\lib\Receiver.js:536:18
    at Receiver.applyExtensions (C:\Users\Administrator\.fie\node_modules\_ws@1.1.5@ws\lib\Receiver.js:371:5)
    at C:\Users\Administrator\.fie\node_modules\_ws@1.1.5@ws\lib\Receiver.js:508:14
    at Receiver.flush (C:\Users\Administrator\.fie\node_modules\_ws@1.1.5@ws\lib\Receiver.js:347:3)
    at Receiver.finish (C:\Users\Administrator\.fie\node_modules\_ws@1.1.5@ws\lib\Receiver.js:541:12)
    at Receiver.expectHandler (C:\Users\Administrator\.fie\node_modules\_ws@1.1.5@ws\lib\Receiver.js:493:33)
    at Receiver.add (C:\Users\Administrator\.fie\node_modules\_ws@1.1.5@ws\lib\Receiver.js:103:24)
    at Socket.realHandler (C:\Users\Administrator\.fie\node_modules\_ws@1.1.5@ws\lib\WebSocket.js:825:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
 Error:can not find the peer :  chrome-debugger[jbg5jnoh64zvg245rlk-0x07]
@(C:\Users\Administrator\.fie\node_modules\_fie-toolkit-nuke@0.7.36@fie-toolkit-nuke\weex-devtool\lib\components\P2PSession.js:115:16)

**Comment by haughtys** [comment]
@hugohua 
。。。
没找到擎空的名字，不知道英文名是什么
希望以后要求@的话，给出正确的名字

**Comment by cloudswindow** [comment]
这是报错里@出来的。。。。貌似是版本的缘故，使用了正确的node版本之后没这个问题了

**Comment by hugohua** [comment]
他离职了，已更新联系人
