### ISSUE TITLE
启动调试时报错

### ISSUE THREAD

**Issue by byzhangkui** [fieteam/fie#72]
TypeError: this.emit is not a function
    at WebSocket.socket.on (/Users/zhangkui/.fie/node_modules/_koa-websocket@2.1.0@koa-websocket/index.js:25:10)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at Receiver.onerror (/Users/zhangkui/.fie/node_modules/_ws@1.1.5@ws/lib/WebSocket.js:876:10)
    at Receiver.error (/Users/zhangkui/.fie/node_modules/_ws@1.1.5@ws/lib/Receiver.js:321:10)
    at Receiver.maxPayloadExceeded (/Users/zhangkui/.fie/node_modules/_ws@1.1.5@ws/lib/Receiver.js:389:8)
    at Receiver.<anonymous> (/Users/zhangkui/.fie/node_modules/_ws@1.1.5@ws/lib/Receiver.js:479:20)
    at Receiver.add (/Users/zhangkui/.fie/node_modules/_ws@1.1.5@ws/lib/Receiver.js:103:24)
    at Socket.realHandler (/Users/zhangkui/.fie/node_modules/_ws@1.1.5@ws/lib/WebSocket.js:825:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)

**Comment by hugohua** [comment]
node版本太低了，升级到 6+ 就行
