### ISSUE TITLE
ding init 后 fie 报错找不到 package.json

### ISSUE THREAD

**Issue by aiic03** [fieteam/fie#73]
你好，我正在按照钉钉Rax应用文档的初始化步骤新建项目（[文档地址](https://open-doc.dingtalk.com/docs/doc.htm?spm=a219a.7629140.0.0.KiNsqq&treeId=357&articleId=107536&docType=1#s1)），发现以下报错：

```
[15:19:12] aichaodeMacBook-Pro-2:rax-demo aichao.ac$ ding init -v
[fie-error] 运行报错, 请在这里反馈问题给 @擎空 @宇果 https://github.com/fieteam/fie/issues/new
Error: ENOENT: no such file or directory, open '/Users/aichao.ac/.fie/package.json'
    at Object.fs.openSync (fs.js:653:18)
    at Object.fs.readFileSync (fs.js:554:33)
    at Object.<anonymous> (/Users/aichao.ac/.fie/node_modules/_pjson@1.0.9@pjson/pjson.js:4:19)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/aichao.ac/.fie/node_modules/_javascript-obfuscator@0.14.3@javascript-obfuscator/dist/index.js:24:55083)
    at t (/Users/aichao.ac/.fie/node_modules/_javascript-obfuscator@0.14.3@javascript-obfuscator/dist/index.js:24:155)
    at Object.module.exports.Object.defineProperty.value (/Users/aichao.ac/.fie/node_modules/_javascript-obfuscator@0.14.3@javascript-obfuscator/dist/index.js:24:265932)
    at t (/Users/aichao.ac/.fie/node_modules/_javascript-obfuscator@0.14.3@javascript-obfuscator/dist/index.js:24:155)
    at Object.<anonymous> (/Users/aichao.ac/.fie/node_modules/_javascript-obfuscator@0.14.3@javascript-obfuscator/dist/index.js:24:22788)
    at t (/Users/aichao.ac/.fie/node_modules/_javascript-obfuscator@0.14.3@javascript-obfuscator/dist/index.js:24:155)
```

**Comment by hugohua** [comment]
重新安装即可

**Comment by aiic03** [comment]
OK，I'll try it. @hugohua
