### ISSUE TITLE
初始化fie init qnui报错

### ISSUE THREAD

**Issue by ft19950915** [fieteam/fie#80]
platform unsupported babel-cli@6.7.7 › chokidar@1.7.0 › fsevents@^1.0.0 Package                                                                                                                 require os(darwin) not compatible with your platform(win32)
[fsevents@^1.0.0] optional install error: Package require os(darwin) not compati                                                                                                                ble with your platform(win32)
Downloading binary from https://cdn.npm.taobao.org/dist/node-sass/v3.13.1/win32-                                                                                                                x64-57_binding.node
Cannot download "https://cdn.npm.taobao.org/dist/node-sass/v3.13.1/win32-x64-57_                                                                                                                binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080
Building: E:\学习软件\Node\node.exe E:\vs2012代码\kdb-qianniu\node_modules\_node                                                                                                                -gyp@3.7.0@node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_c                                                                                                                flags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'E:\\学习软件\\Node\\node.exe',
gyp verb cli   'E:\\vs2012代码\\kdb-qianniu\\node_modules\\_node-gyp@3.7.0@node-                                                                                                                gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.7.0
gyp info using node@8.11.3 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb download using dist-url https://cdn.npm.taobao.org/dist/node
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\vs2012代码\kdb-qianniu\node_                                                                                                                modules\_which@1.3.1@which\which.js:13:12)
gyp verb `which` failed     at F (E:\vs2012代码\kdb-qianniu\node_modules\_which@                                                                                                                1.3.1@which\which.js:68:19)
gyp verb `which` failed     at E (E:\vs2012代码\kdb-qianniu\node_modules\_which@                                                                                                                1.3.1@which\which.js:80:29)
gyp verb `which` failed     at E:\vs2012代码\kdb-qianniu\node_modules\_which@1.3                                                                                                                .1@which\which.js:89:16
gyp verb `which` failed     at E:\vs2012代码\kdb-qianniu\node_modules\_isexe@2.0                                                                                                                .0@isexe\index.js:42:5
gyp verb `which` failed     at E:\vs2012代码\kdb-qianniu\node_modules\_isexe@2.0                                                                                                                .0@isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\vs2012代码\kdb-qianniu\node_                                                                                                                modules\_which@1.3.1@which\which.js:13:12)
gyp verb `which` failed     at F (E:\vs2012代码\kdb-qianniu\node_modules\_which@                                                                                                                1.3.1@which\which.js:68:19)
gyp verb `which` failed     at E (E:\vs2012代码\kdb-qianniu\node_modules\_which@                                                                                                                1.3.1@which\which.js:80:29)
gyp verb `which` failed     at E:\vs2012代码\kdb-qianniu\node_modules\_which@1.3                                                                                                                .1@which\which.js:89:16
gyp verb `which` failed     at E:\vs2012代码\kdb-qianniu\node_modules\_isexe@2.0                                                                                                                .0@isexe\index.js:42:5
gyp verb `which` failed     at E:\vs2012代码\kdb-qianniu\node_modules\_isexe@2.0                                                                                                                .0@isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundE                                                                                                                rror (E:\\vs2012代码\\kdb-qianniu\\node_modules\\_which@1.3.1@which\\which.js:13                                                                                                                :12)\n    at F (E:\\vs2012代码\\kdb-qianniu\\node_modules\\_which@1.3.1@which\\w                                                                                                                hich.js:68:19)\n    at E (E:\\vs2012代码\\kdb-qianniu\\node_modules\\_which@1.3.                                                                                                                1@which\\which.js:80:29)\n    at E:\\vs2012代码\\kdb-qianniu\\node_modules\\_whi                                                                                                                ch@1.3.1@which\\which.js:89:16\n    at E:\\vs2012代码\\kdb-qianniu\\node_modules                                                                                                                \\_isexe@2.0.0@isexe\\index.js:42:5\n    at E:\\vs2012代码\\kdb-qianniu\\node_mo                                                                                                                dules\\_isexe@2.0.0@isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:1                                                                                                                52:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python E:\学习软件\python\python.EXE
gyp verb check python version `E:\学习软件\python\python.EXE -c "import platform                                                                                                                ; print(platform.python_version());"` returned: "3.6.0\r\n"
gyp verb could not find "E:\学习软件\python\python.EXE". checking python launche                                                                                                                r
gyp verb could not find "E:\学习软件\python\python.EXE". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "E:\学习软件\python\python.EX                                                                                                                E", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (E:\vs2012代码\kdb-qianniu\node_                                                                                                                modules\_node-gyp@3.7.0@node-gyp\lib\configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (E:\vs2012代码\kdb-qianniu\node_m                                                                                                                odules\_node-gyp@3.7.0@node-gyp\lib\configure.js:517:16)
gyp ERR! stack     at E:\vs2012代码\kdb-qianniu\node_modules\_graceful-fs@4.1.11                                                                                                                @graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "E:\\学习软件\\Node\\node.exe" "E:\\vs2012代码\\kdb-qianniu\\no                                                                                                                de_modules\\_node-gyp@3.7.0@node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "-                                                                                                                -libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd E:\vs2012代码\kdb-qianniu\node_modules\_node-sass@3.13.1@node-sass
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
Build failed with error code: 1
Error: post install error, please remove node_modules before retry!
Run "C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js" error, exit cod                                                                                                                e 1
    at ChildProcess.proc.on.code (C:\Users\fengtao\.fie\node_modules\_runscript@                                                                                                                1.3.0@runscript\index.js:74:21)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
npminstall version: 2.30.1
npminstall args: E:\学习软件\Node\node.exe C:\Users\fengtao\.fie\node_modules\_n                                                                                                                pminstall@2.30.1@npminstall\bin\install.js --registry=http://registry.npm.taobao                                                                                                                .org/ --china --stdio=inherit --cwd=E:\vs2012代码\kdb-qianniu
'tnpm' ▒▒▒▒▒ڲ▒▒▒▒ⲿ▒▒▒Ҳ▒▒▒ǿ▒▒▒▒еĳ▒▒▒
▒▒▒▒▒▒▒▒▒ļ▒▒▒
[core-error] 运行报错, 请在这里反馈问题给 hugohua https://github.com/fieteam/fie                                                                                                                /issues/new
Error: install  error
    at ChildProcess.spawn.on.on (C:\Users\fengtao\.fie\node_modules\_fie-npm@1.3                                                                                                                .5@fie-npm\lib\index.js:53:18)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at ChildProcess.cp.emit (C:\Users\fengtao\.fie\node_modules\_cross-spawn@5.1                                                                                                                .0@cross-spawn\lib\enoent.js:40:29)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)

**Comment by yubhbh** [comment]
你好.提供一下报错环境和截个图。
以下你可以试一下：
1. 建议用git bash 命令行工具，用管理员身份打开
2. 请确保你的node版本是6 + 
3. 删除 掉node_modules 重试。

**Comment by ft19950915** [comment]
是用的git bash   node是6.14   删掉node_modules文件夹是删除项目中的文件还是  .fie里面的

**Comment by ft19950915** [comment]
![image](https://user-images.githubusercontent.com/31784772/43036746-a371e90a-8d39-11e8-836d-5a10767a2f29.png)
![image](https://user-images.githubusercontent.com/31784772/43036757-c7ab4fd2-8d39-11e8-878a-ece1b46b2b9a.png)

**Comment by ft19950915** [comment]
@yubhbh

**Comment by fattydevelop** [comment]
项目运行时的控制器中是否有报错，麻烦提供一下

**Comment by jjcl521** [comment]
同样的问题，不知道是否已经解决
