### ISSUE TITLE
升级QAP之后一直打不开debug  项目无法调试

### ISSUE THREAD

**Issue by Enjurokcc** [fieteam/fie#84]
qap  debug  error : 

/Users/linyuanfeng/.fie/node_modules/_koa-bodyparser@4.2.1@koa-bodyparser/index.js:72
  return async function bodyParser(ctx, next) {
               ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/linyuanfeng/.fie/node_modules/_fie-toolkit-nuke@0.9.2@fie-toolkit-nuke/weex-devtool/lib/DebugServer.js:9:18)

//版本
node -v --> 6.11.2
npm -v --> 3.10.10

**Comment by fattydevelop** [comment]
升级node到8.0以上
