### ISSUE TITLE
qap init 报错

### ISSUE THREAD

**Issue by 7revor** [fieteam/fie#86]
[core-error] 运行报错, 请在这里反馈问题给 hugohua https://github.com/fieteam/fie/issues/new
C:\Users\Administrator\.fie\node_modules\_koa-static@5.0.0@koa-static\index.js:39
    return async function serve (ctx, next) {
                 ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Administrator\.fie\node_modules\_weex-debugger@1.1.19@weex-debugger\lib\server\index.js:5:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Administrator\.fie\node_modules\_weex-debugger@1.1.19@weex-debugger\lib\index.js:17:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
PS E:\workSpace>

**Comment by fattydevelop** [comment]
升级node 到8.0以上
